VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ub14"


#  config.vm.network :forwarded_port, guest: 22, host: 2223, id: 'ssh'
#  config.vm.network :private_network, ip: "10.0.0.13"
#  config.ssh.forward_agent = true
  config.vm.network "public_network", bridge: "eth0", ip: "192.168.88.153", use_dhcp_assigned_default_route: true


  config.vm.host_name = "cluster3"
  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2400"]
   end

end
